name: travel_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^5.2.3
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  intl: ^0.17.0
  dio: ^4.0.6
  flutter_svg: ^1.1.6
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  stacked_themes: ^0.3.9
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.6.0
  google_fonts: ^3.0.1
  flutter_native_splash: ^2.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
  
  fonts:
  - family: SF_UI_DISPLAY
    fonts:
      - asset: sf_ui_display.ttf
      # - asset: Switzer-BlackItalic.otf
      # - asset: Switzer-Bold.otf
      # - asset: Switzer-BoldItalic.otf
      # - asset: Switzer-Extrabold.otf
      # - asset: Switzer-ExtraboldItalic.otf
      # - asset: Switzer-Extralight.otf
      # - asset: Switzer-ExtralightItalic.otf
      # - asset: Switzer-Italic.otf
      # - asset: Switzer-Light.otf
      # - asset: Switzer-LightItalic.otf
      # - asset: Switzer-Medium.otf
      # - asset: Switzer-MediumItalic.otf
      # - asset: Switzer-Regular.otf
      # - asset: Switzer-Semibold.otf
      # - asset: Switzer-SemiboldItalic.otf
      # - asset: Switzer-Thin.otf
      # - asset: Switzer-ThinItalic.otf
